backend:
  name: github
  repo: carlseag/blog-cf
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDatetime", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["Blog"]}
      - {label: "Body", name: "body", widget: "markdown"}
